### PR TITLE
Fixes #36 Add preconditions on all spec objects. Add RabbitClusterValidator…

### LINKED ISSUE #36: Improve management API error handling and preconditions
For most (all?) of the management API calls we just catch the exception and move on. A few ways we might improve this:
- Be more specific about what exception we're catching
- Do something smarter than just logging
- Validate the input before we call the API

### PR DESCRIPTION
**Pull request by bfink13**
… interface and implementations for validating OperatorPolicy, Policy, and User prior to reconciliation

### CODE REVIEW

File: rabbitmq-operator-model/src/main/java/com/indeed/operators/rabbitmq/model/crd/rabbitmq/AddressAndVhost.java [hunk 1]
```diff
@@ -18,6 +20,9 @@ public AddressAndVhost(
             @JsonProperty("address") final String address,
             @JsonProperty("vhost") final String vhost
     ) {
+        Preconditions.checkArgument(!Strings.isNullOrEmpty(address), "'address' cannot be null");
```
Comment (jhamacher-indeed) [inline rabbitmq-operator-model/src/main/java/com/indeed/operators/rabbitmq/model/crd/rabbitmq/AddressAndVhost.java]: Nit: "cannot be null or empty" or words to that effect, to more closely resemble the actual test?

File: rabbitmq-operator-model/src/main/java/com/indeed/operators/rabbitmq/model/crd/rabbitmq/VhostPermissions.java [hunk 2]
```diff
@@ -24,8 +26,10 @@ public VhostPermissions(
             @JsonProperty("vhostName") final String vhostName,
             @JsonProperty("permissions") final VhostOperationPermissions permissions
     ) {
+        Preconditions.checkArgument(!Strings.isNullOrEmpty(vhostName), "vhost permissions 'name' cannot be empty or null");
```
Comment (jhamacher-indeed) [inline rabbitmq-operator-model/src/main/java/com/indeed/operators/rabbitmq/model/crd/rabbitmq/VhostPermissions.java]: Copy/paste error in the message.

**Review by jhamacher-indeed — APPROVED** [review]
Love this - I wish all of the software I used had such clear messages on bad configuration.

Couple minor comments, nothing major.
